Repository 42JalS/url-shortener, pull requests merged in 2021-11, with the labels that each got.

#1 yunselee
  src/bijective.js
  src/models.js
  src/server.js
Labels: good first issue

#32 클라이언트가 originalUrl을 제공하지 않았을 경우, Bad Request 반환
  controllers/urls.controller.js
Labels: bug

#42 logger 추가
  loaders/express.js
  loaders/winston.js
  package-lock.json
  package.json
  routes/index.js
  routes/test.route.js
Labels: enhancement

#46 📦 NEW: Connect MongoDB Atlas
  config/index.js
  controllers/title.urls.controller.js
  controllers/urls.controller.js
  controllers/urls.custom.controller.js
  controllers/urls.emoji.controller.js
  controllers/urls.original.controller.js
  loaders/mongoose.js
  routes/index.js
  routes/urls.emoji.route.js
  services/title.urls.service.js
  services/urls.emoji.service.js
  services/urls.service.js
Labels: enhancement
